#include <xc.h>
#include <stdint.h>
#include <string.h>

#include "Ui.h"

void uiCalibrationModeScreen(void)
{
	memcpy(
		uiState.screen,
		"CALIBRATION MODE\0"
		"                ",
		sizeof(uiState.screen));

	uiState.input.buttons = (const struct ButtonsBehaviour *) 0;
	uiScreenBlit();

	// TODO: NEED TO ENSURE THE SCREEN IS OFF / STAYS OFF SO VOLTAGE REGULATOR DOESN'T INTERFERE WITH ANYTHING; BUTTON HANDLING AUTOMATICALLY TURNS THE SCREEN ON, SO ADD AN OVERRIDE FLAG OR SOMETHING TO PREVENT THAT...
	// TODO: CANNOT USE SOSC AS BRG SOURCE FOR UART...THINK OF SOMETHING ELSE !  MANCHESTER ENCODING ?
	// TODO: USE UART WITH RB6 AS CK, RB7 AS RX/TX FOR COMMS; THE CLOCK WILL NEED TO BE 32.768kHz / 8 = 4.096kHz TO GIVE A SUITABLE PERIOD FOR HANDLING THE MESSAGES
	// THE CRYSTAL WILL BE THE CLOCK, ALLOWING MEASUREMENT WITH A FREQUENCY COUNTER
	// THE UART WILL BE MASTER MODE WITH CONTINUAL RECEPTION
}
