sudo: required

addons:
  apt:
    packages:
      - libc6:i386
      - libx11-6:i386
      - libxext6:i386
      - libstdc++6:i386
      - libexpat1:i386

install:
  - src/firmware/build/install-mplabx.sh

script:
  - src/firmware/ceedling
