:project:
  :build_root: build/ceedling/generated
  :test_file_prefix: Test
  :which_ceedling: build/ceedling/vendor/ceedling
  :use_exceptions: FALSE
  :release_build: TRUE
  :default_tasks:
    - test:all

:environment:
  - :mcu: PIC16F15355
  - :path:
    - /bin
    - /usr/bin
    - /opt/microchip/xc8/v2.05/bin
    - build

:extension:
  :object: .o
  :executable: .elf
  :assembly: .S

:paths:
  :test:
    - tests/**
  :source:
    - src/**
  :include:
    - /opt/microchip/xc8/v2.05/pic/include

:files:
  :source:

  :assembly:
    - +:src/SunEvents/SunEventsTables.S

  :support:
    - +:src/ConfigurationWords.c
    - +:src/NvmSettings.c
    - +:tests/unity_config.c
    - +:tests/NonDeterminism.c

:defines:
  :commmon: &common_defines []
  :test:
    - *common_defines
    - TEST
  :test_preprocess:
    - *common_defines
    - TEST

:release_build:
  :output: Cluck3Sesame.elf
  :use_assembly: TRUE

:unity:
  :defines:
    - UNITY_INCLUDE_CONFIG_H

:cmock:
  :mock_prefix: Mock_
  :when_no_prototypes: :warn
  :treat_externs: :include
  :enforce_strict_ordering: TRUE
  :fail_on_unexpected_calls: FALSE
  :defines:
    - CMOCK_MEM_SIZE=256
  :plugins:
    - :ignore
    - :ignore_arg
    - :callback
    - :expect_any_args

:tools:
  :release_compiler:
    :name: "Microchip XC8 Compiler"
    :executable: xc8-cc
    :arguments:
      - "-mcpu=#{ENV['MCU']}"
      - -std=c99
      - -O2
      - -Wa,-a
      - -D"$": COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -I"$": COLLECTION_PATHS_SOURCE_AND_INCLUDE
      - -o "${2}"
      - -c
      - "${1}"

  :release_assembler:
    :name: "Microchip XC8 Compiler"
    :executable: xc8-cc
    :arguments:
      - "-mcpu=#{ENV['MCU']}"
      - -std=c99
      - -O2
      - -Wa,-a
      - -D"$": COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -I"$": COLLECTION_PATHS_SOURCE_AND_INCLUDE
      - -o "${2}"
      - -c
      - "${1}"

  :release_linker:
    :name: "Microchip XC8 Linker"
    :executable: xc8-cc
    :arguments:
      - "-mcpu=#{ENV['MCU']}"
      - -gdwarf-3
      - -D"$": COLLECTION_DEFINES_RELEASE_AND_VENDOR
      - -I"$": COLLECTION_PATHS_SOURCE_AND_INCLUDE
      - -Wl,-Map="${3}"
      - -Wl,-AID=0x8006-0x8007
      - -Wl,-PID=ID
      - -Wl,-PNvmSettings=0x1fe0
      - --fill=0x3fff
      - -mserial=0000@8005
      - -mserial=ae30@8006
      - -o "${2}"
      - "#{'${1}'.split(' ').map { |x| (x.include? '/out/c/') ? (Pathname(x).sub_ext '.p1').to_s : x }.join(' ') }"
      - "${4}"

  :test_compiler:
    :name: "Microchip XC8 Compiler"
    :executable: xc8-cc
    :arguments:
      - "-mcpu=#{ENV['MCU']}"
      - -std=c99
      - -O2
      - -Wa,-a
      - -D"$": COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -o "${2}"
      - -c
      - "${1}"

  :test_linker:
    :name: "Microchip XC8 Linker"
    :executable: xc8-cc
    :arguments:
      - "-mcpu=#{ENV['MCU']}"
      - -gdwarf-3
      - -D"$": COLLECTION_DEFINES_TEST_AND_VENDOR
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -Wl,-Map="${3}"
      - -Wl,-AID=0x8006-0x8007
      - -Wl,-PID=ID
      - -Wl,-PNvmSettings=0x1fe0
      - --fill=0x3fff
      - -mserial=0000@8005
      - -mserial=ae30@8006
      - -o "${2}"
      - "#{'${1}'.split(' ').map { |x| (x.include? '/out/c/') ? (Pathname(x).sub_ext '.p1').to_s : x }.join(' ') }"
      - src/SunEvents/SunEventsTables.S
      - "${4}"

  :test_fixture:
    :name: "Microchip MPLABX Simulator"
    :executable: run-test.sh
    :arguments:
      - mdb
      - "#{ENV['MCU']}"
      - "${1}"
      - "tests"
      - "#{(Pathname('${1}').sub_ext '.fixture').basename}"

:plugins:
  :load_paths:
    - build/ceedling/vendor/ceedling/plugins
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - raw_output_report
    - warnings_report
