#ifndef __CLUCK3SESAME_SRC_PLATFORM_CALIBRATIONMODE_H
#define __CLUCK3SESAME_SRC_PLATFORM_CALIBRATIONMODE_H

#define CALIBRATIONMODE_CMD_REFCLK 'C'
#define CALIBRATIONMODE_CMD_READ 'R'
#define CALIBRATIONMODE_CMD_SAMPLEPARAMETERS 'S'
#define CALIBRATIONMODE_CMD_EOL '\n'

#define CALIBRATIONMODE_REPLY_OK 'O'
#define CALIBRATIONMODE_REPLY_ERROR 'E'

extern void calibrationModeInitialise(void);

#endif
