#include <xc.h>

#pragma config "FEXTOSC=OFF"
#pragma config "RSTOSC=HFINT32"
#pragma config "CLKOUTEN=OFF"
#pragma config "CSWEN=ON"
#pragma config "FCMEN=OFF"
#pragma config "MCLRE=ON"
#pragma config "PWRTE=ON"
#pragma config "LPBOREN=OFF"
#pragma config "BOREN=OFF"
#pragma config "ZCD=OFF"
#pragma config "PPS1WAY=OFF"
#pragma config "STVREN=ON"
#pragma config "WDTE=OFF"
#pragma config "BBEN=OFF"
#pragma config "SAFEN=OFF"
#pragma config "WRTAPP=OFF"
#pragma config "WRTB=OFF"
#pragma config "WRTC=ON"
#pragma config "WRTSAF=OFF"
#pragma config "LVP=ON"
#pragma config "CP=OFF"
