#include <xc.h>

#pragma config "FEXTOSC=HS"
#pragma config "RSTOSC=EXT4X"
#pragma config "CLKOUTEN=OFF"
#pragma config "CSWEN=OFF"
#pragma config "FCMEN=OFF"
#pragma config "MCLRE=ON"
#pragma config "PWRTE=ON"
#pragma config "LPBOREN=ON"
#pragma config "BOREN=ON"
#pragma config "ZCD=OFF"
#pragma config "PPS1WAY=OFF"
#pragma config "STVREN=ON"
#pragma config "WDTE=OFF"
#pragma config "BBEN=OFF"
#pragma config "SAFEN=OFF"
#pragma config "WRTAPP=OFF"
#pragma config "WRTB=OFF"
#pragma config "WRTC=OFF"
#pragma config "WRTSAF=OFF"
#pragma config "LVP=ON"
#pragma config "CP=OFF"
